#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################

language: java

sudo: required

services:
  - docker

env:
 global:
   - JAVA_OPTS="-XX:MaxPermSize=512m"
 matrix:
   - SUITE=containers
   - SUITE=images
   - SUITE=docker-misc
   - SUITE=git,remote-copy

script:
  - chmod +x ci-env/travis/run_containers.sh && ci-env/travis/run_containers.sh
  - docker ps -a
  - docker info
  - docker version
  - df -kh
  - wget https://www.dropbox.com/s/k23flttxzq112hv/cslang-builder.zip
  - unzip -q cslang-builder.zip -d cslang-builder
  - chmod +x cslang-builder/bin/cslang-builder
  - ./cslang-builder/bin/cslang-builder -ts ${SUITE},\!default -cov
    
# cat prints only part of the file for some reason so we print ourselves
after_failure: while read line; do printf "%s\n" "$line"; done < builder.log
